<?php

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class OAuthTest extends TestCase
{
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->providerName = 'github';
    }

    public function github()
    {
        $this->get(route('socialOAuth', ['provider' => $this->providerName]))->assertStatus(200);
    }

    public function githubRegist()
    {
        $this->get(route('oauthCallback',['provider' => $this->providerName]))->assertStatus(200);
    }

}
